version: "3.0"
services:
  job_board_db:
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=job_board
    ports:
      - '5432:5432'

  job_board:
    image: leobz/job_board:latest
    environment:
      - DB_NAME=job_board_db
    ports:
      - '3000:3000'
    depends_on:
      - job_board_db

volumes:
  db-data:
    driver: local
